apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviesapp
  labels:
    app: moviesapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviesapp
  template:
    metadata:
      labels:
        app: moviesapp
    spec:
      containers:
        - name: moviesapp
          image: matthewlemmond/python_api:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
